apiVersion: v1
kind: ConfigMap
metadata:
  name: crondir
data:
  crontab: |
    0 0 * * * /usr/local/bin/wgetfromthredds.sh
---
apiVersion: v1
kind: Pod
metadata:
  name: ocdp
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  shareProcessNamespace: true
  containers:
    - name: app
      image: ocdp
      env:
      - name: LC_ALL
        value: C.utf8
      ports:
      - name: http
        containerPort: 3838
        hostPort: 3838
        protcol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: http
      securityContext: &containerSecurityContext
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: data
          mountPath: /srv/shiny-server/data
    - name: cron
      image: ocdp
      args:
        - /usr/local/bin/supercronic
        - /etc/cron.d/crontab
      env:
      - name: LC_ALL
        value: C.utf8
      securityContext: *containerSecurityContext
      volumeMounts:
        - name: crondir
          mountPath: /etc/cron.d
  volumes:
    - name: crondir
      configMap:
        name: crondir
    - name: data
      hostPath:
        path: ./data
